plugins/deviantart_a.js
plugins/tumblr_a.js

Use https for ajax requests so they will work when on an https page. This is a problem now that Reddit is only available over https.
Some of the other plugins might need to be updated as well.

Use https for ajax requests.

---

plugins/twitter.js

Changes taken from the original extension.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/22)

Fix twitter images

---

js/options.js

there is a typo in the css selector for mouse wheel option

fix for #26

---

_locales/de/messages.json
_locales/en/messages.json
_locales/hr/messages.json
_locales/it/messages.json
_locales/pt_BR/messages.json
_locales/ru/messages.json
_locales/tr/messages.json
html/options.html
js/common.js
js/hoverzoom.js
js/options.js
manifest.json

Hey extesy! 
I made the option to only scroll through albums and not videos. However, I only made the english localization and Italian.
The rest of them are included but still just in regular English.
Let me know if you need anything else or have any questions!

Add option to have mousewheel scroll through albums only and not videos

---

plugins/imgur_a.js

Like : http://i.stack.imgur.com/sgKzK.jpg

Handle host `i.stack.imgur.com`

---

_locales/ru/messages.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/137)

Typo in russian translation

---

manifest.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/162)

Add support for amazon.in

---

manifest.json
plugins/artuk.js
plugins/flipkart.js

Resolves issues #160 and #158
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/167)

Adds support for flipkart.com and artuk.org

---

plugins/fetlife.js

FetLife updated their image serving to require some kind of CSRF-style token to view any image.  This loads the actual picture page in order to get the full source (with token).  Previously just swapping the resolution suffix was enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/168)

Updated FetLife with Cache Tokens

---

manifest.json
plugins/carrefoursa.js
plugins/n11.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/170)

Added support for n11.com and carrefoursa.com

---

plugins/n11.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/173)

Enable HoverZoom for unloaded images on n11.com.

---

js/hoverzoom.js
manifest.json
plugins/ask.js

Fixes #151. As ask.fm constantly keeps deleting and recreating it's
body, #hzImg is constantly being removed (and not added back in, as the
internal data structure is not updated accordingly). Because the whole
body is being removed, I added a MutationObserver that observes the
html-element for changes, and if #hzImg has been removed the data
structure is updated acordingly (hoverzoom.hzImg is set to false).
I also removed two tabstops in manifest.json, and replaced them with
spaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/174)

Added support for ask.fm

---

manifest.json
plugins/instagram.js

Added support for instagram.com

---

plugins/boardgamegeek.js

Fix for plugin: boardgamegeek.js

---

plugins/freepik.js

Plugin fixed + "version" added.

Fix for plugin: freepik.js

---

_locales/da/messages.json
_locales/de/messages.json
_locales/en/messages.json
_locales/es/messages.json
_locales/fa/messages.json
_locales/fi/messages.json
_locales/fr/messages.json
_locales/hr/messages.json
_locales/id/messages.json
_locales/it/messages.json
_locales/ko/messages.json
_locales/nl/messages.json
_locales/pt_BR/messages.json
_locales/ru/messages.json
_locales/sv/messages.json
_locales/tr/messages.json
html/options.html
js/common.js
js/hoverzoom.js
js/options.js

Partially addresses issue #171. Currently only has English translations.

Added option to customize caption location

---

_locales/en/messages.json
html/options.html
js/common.js
js/hoverzoom.js
js/options.js

Partially addresses issue #171

Add option to center images

---

manifest.json
plugins/artlimited.js

Added plugin for: artlimited.net

---

js/hoverzoom.js
manifest.json
plugins/alicdn.js

Add support for tmall.com

---

manifest.json
plugins/pixabay.js

Free pictures & videos under Creative Commons CC0 licence.

Added plugin for: Pixabay.com

---

manifest.json
plugins/artstation.js

ArtStation is the showcase platform for games, film, media & entertainment artists.

Added plugin for: ArtStation.com

---

manifest.json
plugins/artsper.js

Added plugin for: Artsper.com

---

manifest.json
plugins/istockphoto.js

iStock is part of the Getty Images family of companies.

Added plugin for: iStockPhoto.com

---

manifest.json
plugins/everystockphoto.js

Everystockphoto.com is a license-specific photo search engine.

Added plugin for: EveryStockPhoto.com

---

plugins/fetlife.js

FetLife's feed can have LOTS of thumbnails next to each other (someone can like 50+ photos, and it'll show them in a 7xWhatever grid).  Previously, it was really easy to sweep a bunch of images with the mouse to trigger lots of requests, both hammering and FetLife and causing HoverZoom to flicker lots of different full size images.
Not sure how to address the larger flicker/UI issue when that was happening, so just delayed the prepareFromDocument() call.

Delay Secondary Request

---

manifest.json
plugins/smugmug.js

Paid photo-sharing website and image hosting service.

Added plugin for: SmugMug.com

---

manifest.json
plugins/cgcookie.js

An online Computer Graphics education site.

Added plugin for: CgCookie.com

---

manifest.json
plugins/dreamstime.js

53 million stock images, world's largest stock community, 16 million users.

Added plugin for: dreamstime.com

---

manifest.json
plugins/cgsociety.js

The CGSociety supports artists at every level by offering a range of services to connect, inform, educate and promote digital artists worldwide.

Added plugin for: CGSociety.org

---

manifest.json
plugins/mobypicture.js

Directly share your photos, videos and audio with your friends on your favorite social sites: facebook, twitter, flickr, youtube, and more!

Added plugin for: Mobypicture.com

---

manifest.json
plugins/foursquare.js

Find the best places to eat, drink, shop, or visit in any city in the world. Access over 75 million short tips from local experts.

Added plugin for: Foursquare.com

---

manifest.json
plugins/metmuseum.js

Added plugin for: MetMuseum.org

---

plugins/reddit.js

Reddit changed i.reddituploads.com link href to point to the post comments. Changed it to use the same data-url as i.redd.it links. Fixes #235

Fixed reddit i.reddituploads.com

---

manifest.json
plugins/pexels.js

Free stock photos you can use everywhere. ✓ Free for commercial use ✓ No
attribution required.

Added plugin for: Pexels.com

---

manifest.json
plugins/adobestock.js

Over 60 million professional high quality royalty free stock photos and video

Added plugin for: Adobe Stock Photos

---

manifest.json
plugins/3dtotal.js

Added plugin for: 3dtotal.com

---

manifest.json
plugins/fubiz.js

Fubiz, Daily Dose of Inspiration

Added plugin for: Fubiz.net

---

manifest.json
plugins/drawcrowd.js

DrawCrowd, a place to fund your creativity

Added plugin for: DrawCrowd.com

---

plugins/facebook.js

This pull request update the code for facebook that now is working :-)

support for facebook

---

js/background.js
package.json

With this fix the extension works without problems on Firefox

Firefox support

---

.eslintrc.yml
.jshintrc
package.json

This PR upgrades ESLint tools and moves configuration to separate YAML file.
I've removed JSHint config. I'm aware that we have a lot of formatting mess in code, but at least we can try to adhere to style for newly developed plugins or code.

Upgrade ESLint, fix config file

---

manifest.json
plugins/clippituser_a.js

Adds a plugin for https://clippituser.tv/ which I've started to see in some reddit threads as an alternative to streamable.

Add clippituser.tv plugin

---

_locales/en/messages.json
css/spectrum.css
html/options.html
js/common.js
js/hoverzoom.js
js/libs/spectrum.js
js/options.js

Fixes #262
This pr adds the ability for the user to choose their own colour for the hoverzoom frame. So far the new option in the options screen is only in english.
Choosing a new colour:
The new colour in action:

Added ability to change frame colour

---

js/hoverzoom.js
plugins/instagram.js
plugins/pinterest.js
plugins/pixiv.js

Also, a small refactoring of code that was used in both plugins and probably in others a well.
(tell me if you don't like the function name, I was a bit undecided)
Completes #381.
Closes #332.

Fix Pixiv, Instagram, Pinterest

---

plugins/bing.js

Bing had changed the name from imgurl to murl

Resolved the issue of the image not loading in Bing

---

plugins/gfycat.js

Support for Lang in URL in Gfycat plugin

---

plugins/reddit.js

Fixes issue with v.redd.it links not loading as mentioned in #435.
The root cause was Chrome 73's change to disallow cross origin requests from content scripts. This updates the reddit script to send a message to the background script, which can still make cross origin requests, to get the DASH playlist XML. More details on the Chrome changes can be found here: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

Use background script to make ajax requests for reddit videos

---

plugins/pixiv.js

Added support to differentiate between single pixture and gallery and show galleries as such.

Gallery support pixiv

---

manifest.json
plugins/pixiv.js

Fixed pixiv gallery view to work with the new way pixiv shows galleries

Fix to pixiv gallery

---

plugins/pixiv.js

Issue : #462 
What i change : 
1. Removing $.get() , instead i change it to RegExp
2. Updated /artwork/ url

#462 "Improving" Pixiv Hoverzoom

---

plugins/google.js

This new version of plug-in catches "on the fly" data sent by Google servers when user scrolls down images results.
Note: this method could be applied to other plug-ins, removing the need for API calls.

Rewrite of Google Images plug-in

---

js/hoverzoom.js
plugins/instructables.js
plugins/modelmayhem.js

+ fix for plug-in: ModelMayhem
+ minor adujstement for plug-in: Instructables
+ comments added to main js script

Fix for plug-in: ModelMayhem

---

plugins/amazon.js

Fix for plug-in: Amazon

---

manifest.json
plugins/safebooru.js

User request on Chrome Webstore (Daryl Hamor)

New plug-in: Safebooru

---

plugins/bing.js

Fix for detail view on images search results

Fix for plug-in: Bing

---

plugins/steam.js

Added support for background images + regex fix

Fix for plug-in: Steam

---

_locales/en/messages.json
css/style.css
html/options.html
js/common.js
js/hoverzoom.js
js/options.js

Added settings to ambilight option + minor fixes

Improvements to ambilight

---

manifest.json
plugins/google_a.js

Usefull on Google Maps to zoom users provided content

New plug-in for : GoogleUserContent

---

manifest.json
plugins/depositphotos.js

Royalty-free Stock Photos, Vector Images, and Videos

New plug-in: DepositPhotos

---

js/background.js
manifest.json
plugins/facebook.js
plugins/facebook_a.js

This plug-in performs graphQL queries to find fullsize versions of some images.
By the way, some images still refuse to zoom, not because of the plug-in but because of a flaw in HZ+ : fix coming soon!

Fix plug-in for Facebook new design

---

manifest.json
plugins/goodreads.js

Hi!
This loads book covers and user, author, and group profile images.

New plugin: Goodreads

---

js/hoverzoom.js

Checks the presence of an horizontal scroll bar and displays zoomed images accordingly. So borders of zoomed images are not hidden.

Cosmetic changes: better display of zoomed images

---

plugins/facebook.js

New graphQL query added in order to display users' profiles pictures: **ProfileCometHeaderQuery**
@extesy : maybe it's time for a **Xmas release** :santa:

Improvement for Facebook plug-in

---

js/hoverzoom.js

- image loader colors saturation reduced to 25%
- correct handling of urls of type: blob:http...
They are not very common but can be find on whatsapp:  blob:https://web.whatsapp.com/fb375aba-64bd-4d8e-89c6-dc85700e79c2

New colors for image loader + fix on urls normalization

---

manifest.json

Needed to deal with non-US countries (pinterest.fr, pinterest.it,...)

Update manifest for Pinterest plug-in

---

manifest.json
plugins/500px.js
plugins/aminus3.js
plugins/aol.js
plugins/derpibooru.js
plugins/flickr.js
plugins/giphy.js
plugins/imageevent.js
plugins/pikwizard.js
plugins/thingiverse.js

Fix for plug-ins:
- 500px
- Flickr
New plug-ins:
- Aminus3
- AOL
- Derpibooru
- Giphy
- Imageevent
- Pikwizard
- Thingiverse

Fix for 2 plug-ins + 7 new plug-ins

---

manifest.json
plugins/safebooru.js

This update closes #61 (an issue opened in 2016 :open_mouth:)

HZ+ now works on Gelbooru.com

---

manifest.json
plugins/ebay_a.js
plugins/furaffinity.js
plugins/govdeals.js
plugins/imgflip_a.js
plugins/minds.js

- fix for plug-in: furaffinity closes #618
- new plug-in: ebay_a closes #53
- new plug-in: Minds closes #430
- update to manifest closes #251 & #348

Fix for plug-in: furaffinity + new plug-ins + manifest update

---

js/hoverzoom.js
manifest.json
plugins/cloudinary_a.js
plugins/gitlab.js

New plug-ins for: gitlab & cloudinary

---

js/hoverzoom.js

Remove debug logging

---

manifest.json
plugins/hibid.js
plugins/maxsold.js

New plug-ins: Hibid & Maxsold

---

js/hoverzoom.js

Fix img elements title's not being removed

---

manifest.json
plugins/myanimelist.js

Request #744 by @prestidigitonium

New plug-in : MyAnimeList

---

js/hoverzoom.js

Fix for : no sound on Reddit zoomed videos

---

js/hoverzoom.js

Yep, #751 broke captions too :anguished:
I also removed a too restrictive "min size" rule on captions : a caption < 6 characters was skipped.

Fix for captions

---

_locales/en/messages.json
js/common.js
js/hoverzoom.js
js/options.js

- flip images & videos vertically & horizontally
- display zoom scale for images & videos (100% : full size)

New action key: flip + zoom scale display

---

_locales/en/messages.json
css/style.css
html/options.html
js/background.js
js/common.js
js/hoverzoom.js
js/options.js

new option : **hide mouse cursor** after x ms (default value: disabled)
new details : img or video **ratio** (4:3, 16:9, ...), **timestamp** (= last-modified from server), **size** (=content-length from server)

New option + new imgs details

---

manifest.json
plugins/catawiki.js
plugins/themoviedb.js
plugins/twibooru.js

- booru image boards
- catawiki
- TheMovieDB

New plug-ins

---

plugins/mediawiki_a.js

Previous version was not restrictive enough

Improvement of MediaWiki plug-in

---

manifest.json
plugins/sogou.js

Sogou ("searching dog") is a chinese search engine

New plug-in for: Sogou

---

manifest.json
plugins/allegro.js

New plug-in for: Allegro

---

js/hoverzoom.js
plugins/pixiv.js

Updated because of Pixiv new design

Fix for : Pixiv plug-in (#820)

---

js/hoverzoom.js
plugins/startpage.js

I did not clean up other plug-ins (DuckDuckGo, Flickr, Qwant, Sogou) yet. They use slightly different versions of these functions, i'll have to review them first.

Factorization of JSON search functions

---

plugins/twitter.js

This fix adresses avatars issue (#836)

Fix for plug-in: Twitter.js

---

manifest.json
plugins/bing_a.js
plugins/duckduckgo.js
plugins/you.js

+ small fixes for other plug-ins

New plug-in for: You.com

---

js/hoverzoom.js

Fix: video & audio controls hidden when video is not locked

---

js/hoverzoom.js

Replacement of "blink" reserved word

Fix for blink style (#847)

---

js/background.js
plugins/500px.js
plugins/weibo.js

500px requires some additional headers (X-CSRF-TOKEN & X-500PX-TOKEN) when user is logged in.

Fix for plug-in: Weibo & 500px

---

manifest.json
plugins/twitch.js

clips & videos from Twitch are now displayed in Reddit

Fix for plug-in: Twitch

---

_locales/en/messages.json
css/style.css
html/options.html
js/options.js

- User's change(s) are outlined in orange (same as Popup)
- 2 buttons to enable/disable all plugins at once:

Enhancements for Options pages

---

js/hoverzoom.js
manifest.json
plugins/viewbug.js

Also: a fix for image/backgroundImage conflics.
This (rare) situation occurs on viewbug.com

New plug-in for: viewbug.com (#896)

---

js/hoverzoom.js

Audio options (muted & volume) added for playlists (m3u8)

---

manifest.json
plugins/twitch_a.js

Clips can now be played from any website

Fix for Twitch plug-in

---

manifest.json
plugins/shein.js

This pull request addreses #906

New plug-in for: Shein.com (#906)

---

js/hoverzoom.js

This fix improves the way galleries are handled:
- galleries can now contain a mix of images & videos (e.g; Imgur)
- galleries can now contain playlists (m3u8)

Fix for galleries

---

manifest.json
plugins/bilibili.js

Enhancements for plug-in: Bilibili

---

manifest.json
plugins/bilibili_a.js

Bilibili plug-in now works in search engines & other sites

Enhancement: bilibili -> bilibili_a

---

js/hoverzoom.js
manifest.json
plugins/bnf.js

+ enhancement for galleries handling: when number of items in gallery is unknown, items are displayed until load error is raised. Then gallery's size is adjusted.

New plug-in for: bnf.fr

---

_locales/en/messages.json
html/options.html
js/common.js
js/hoverzoom.js
js/options.js

This allows the user to toggle on/off the message added previously in #942. Defaults to enabled.
Still need to test, welcome any feedback.

Add an option to Advanced options tab to toggle NoFocus message visibility

---

js/hoverzoom.js
plugins/default.js

Supported video formats : 3gpp, gif, gifv, m4v, mkv, mp4, ogv, webm

Enhancement for videos

---

plugins/dailymotion_a.js

Short addresses (e.g: https://dai.ly/x4v3maz) are now handled

Fix for plug-in: dailymotion_a

---

plugins/default.js

Not so many of them out there on the internet, samples can be found here: https://ottverse.com/free-hls-m3u8-test-urls/

Support for playlists (M3U8)

---

plugins/youtube_a.js

Address issue #963 : headers must not be modified when initiator =YouTube

fix for plug-in: YouTube_a

---

js/hoverzoom.js

HZ+ can handle:
- images
- videos & playlists
- audio sources (coming soon)
So naming of variables, etc should reflect this.

Code cleaning

---

manifest.json
plugins/niconico_a.js

Niconico is a Japanese video-sharing service on the web. "Niconico" or "nikoniko" is the Japanese ideophone for smiling.

New plug-in for: niconico

---

manifest.json

safebooru.js works for https://mspabooru.com/

Add mspabooru.com

---

js/hoverzoom.js
manifest.json
plugins/moddb.js

This plug-in adresses issue #1003

New plug-in for: moddb.com (#1003)

---

js/hoverzoom.js
manifest.json
plugins/sendvid_a.js

& fix for "dimensions" detail display

New plug-in for: sendvid.com (videos hosting)

---

plugins/tiktok.js
plugins/tiktok_a.js

When enabled, TikTok plug-ins prevented users from posting comments & liking.

Fix for TikTok plug-ins

---

js/hoverzoom.js
plugins/badoo.js

Badoo plug-in needs some more work (=> display gallery on photo profile hovering)

Enhancement for urlReplace function (=> list of filters) + fix for plug-in: Badoo

---

plugins/redgifs.js

The Redgifs plugin doesn't always use the best quality version.
This PR uses the `hd` URL provided by the v2 API to fix that.

Update redgifs to show HD video

---

plugins/redgifs.js

Add selector to match new https://v3.redgifs.com/ links.

Add support for redgifs v3

---

js/BigInteger.js
js/hoverzoom.js
manifest.json
plugins/instagram.js
plugins/instagram_a.js

Rewrite of Instagram plug-ins, you need be logged in for better efficiency. 
Plug-ins handle:
- pictures
- videos
- carousel (it is possible to download distinct audio tracks & subtitles from videos when present)
@extesy 
- i reduced as much as possible API calls because it looks like they trigger temporary ban, could you please check on your side that it's ok ?
- i added a new script (**BigInteger.js**) to compute media id from shortcode. As BigInt is now supported natively by all browsers it should be possible to do without, maybe you know how ?

New plug-ins for: Instagram

---

plugins/reddit.js

Adds handling for single and gallery images on reddit.com.

Zoom Reddit single and gallery images

---

manifest.json
plugins/temu.js

This plug-in zooms images & videos provided by users.

New plug-in for: temu.com (#1069)

---

js/background.js
js/hoverzoom.js
plugins/pixiv.js
plugins/tiktok_a.js

+ headers rewrite for Pixiv & Tiktok

Improvements to download functionality

---

manifest.json
plugins/douyin.js
plugins/douyin_a.js

Douyin = Chinese version of TikTok

New plug-in for: Douyin

---

js/background.js
js/hoverzoom.js

@extesy can you test this fix before release please? Download permission is now only checked when setting options.

Fix for multiple downloads of same file (#1127)

---

js/jszip.js
manifest.json
plugins/pixiv.js

Well, they are not exactly videos but a sequence of static images in a ZIP file. HZ+ plug-in will unzip images & display them in a gallery.

Support for PIXIV "videos" (#1124)

---

js/hoverzoom.js

@extesy callback seems to work fine for me (no duplicate downloads triggered)

Callback added to handle download failure

---

plugins/mediawiki_a.js

- better handling of non-english wikis
- audios & videos files are played

Update for plug-in: mediawiki_a

---

manifest.json
plugins/iwara.js

Works only for images, not videos

New plug-in for: Iwara.tv

---

js/background.js
js/hoverzoom.js
plugins/dailymotion_a.js
plugins/douyin_a.js
plugins/imagefap_a.js
plugins/instagram_a.js
plugins/kick_a.js
plugins/niconico_a.js
plugins/pixiv.js
plugins/rule34video_a.js
plugins/tiktok_a.js
plugins/twitch_a.js
plugins/xhamster_a.js
plugins/youtube_a.js

Headers rewriting is now triggered by a collection of URLs.

Fix for plug-in: Kick.com (#1156) + enhancement of background.js

---

manifest.json
plugins/letterboxd.js

Uses the same plugin code structure as the IMDb plugin

New plug-in for: Letterboxd.com

---

manifest.json
plugins/figma.js
plugins/kleinanzeigen.js

Adds basic plugin for Figma (#953) and kleinanzeigen.de (#1115)

---

plugins/facebook.js

Addresses partially #1160
@extesy i think it is good enough for a release, i'll try to improve it next week.

Rewrite of plug-in for: Facebook (work in progress)

---

plugins/kick_a.js

Fix for plug-in: Kick.com

---

plugins/facebook.js

Yet to be done:
- stories
- live (require MPD handling)

Fix for plug-in: Facebook.com

---

plugins/redgifs.js

I had to redo the commit, creating new pull request. 
About the try {} catch {}. Literally every single JSON.parse is made like that in that repository.

fix cors issue

---

manifest.json
plugins/tcgplayer_a.js

New plug-in for: TCGplayer

---

plugins/redgifs.js

new format appeared 
`redgifs.com/ifr/code `
this change adds support for all redgifs links
https://regex101.com/r/JbbdFZ/1
https://www.reddit.com/domain/redgifs.com/

add support for ifr* redgifs links

---

plugins/anilist.js

Added support for background images

Fix for anilist plug-in (#1166)

---

README.md

I have added dynamic badges next to the extension links in the README.md file. 
The badges display the no. of users of the extension across different browsers.

Added Dynamic Badges Displaying User Counts

---

js/findMatchingBracket.js
js/hoverzoom.js
manifest.json
plugins/deviantart.js

Images & videos (gif, mp4) are now correctly handled.
Note: **when logged in**, downloadable version of images (when available) can be zoomed by hovering the "Free download" icon.
New helper functions:
- **decodeUnicode** : e.g: u002F => /
- **matchBracket** : find matching bracket, useful to extract just a small part of a large JSON chunk of data.

Rewrite of DeviantArt plug-in (#1230) + helper functions

---

js/hoverzoom.js
plugins/gettyimages.js

Rewrite of plug-in: GettyImages (#1261)

---

plugins/facebook.js

Better handling of videos & live

Fix for plug-in: Facebook

---

plugins/dailymotion_a.js

rewrite of header updated so videos can be watched from reddit

Fix for plug-in : dailymotion_a

---

plugins/google_a.js

This PR disabled changes introduced by @GrosPoulet with https://github.com/extesy/hoverzoom/pull/1256, only the lines causing performance issues. Note here that I won't work on fixing regex itself.
Fixes: https://github.com/extesy/hoverzoom/issues/1283

feat: temporarily disable regex causing huge performance issues

---

js/options.js
js/popup.js

Adding Alt key as an option for "Activate HoverZoom+".

---

plugins/naver.js

Added support for live & videos

Fix for plug-in: naver.js (#1296)

---

manifest.json
plugins/media_a.js

for vogue.fr, wired.com, newyorker.com...

New generic plug-in: media_a

---

manifest.json
plugins/podcasts_apple.js

- Podcasts are played when hovering the "Play" button
- HZ+ player allows user to save audio files (.mp3)

New plug-in for: Apple Podcasts

---

manifest.json
plugins/physorg.js

And also:
- medicalxpress.com
- sciencex.com
- techxplore.com

New plug-in for: Phys.org

---

manifest.json
plugins/apple.js

- zoom apps, music & books covers
- play podcasts
- do NOT play music tracks

Plug-in for: Apple (apps, music, podcasts & books)

---

plugins/freepik.js

Fix for plug-in: Freepik.com

---

manifest.json

Update manifest.json for X/Twitter's updated URL

Fix for X/Twitter URL change

---

js/hoverzoom.js
manifest.json
plugins/spotify.js

- play & download audio tracks (does not work for podcasts)
- zoom media (artists, album covers)

New plug-in for : Spotify

---

plugins/spotify.js

Fix for plug-in: Spotify

---

manifest.json
plugins/polona.js

HZ+ will display either a gallery or single image:
- gallery:
- single image:

New plug-in for: polona.pl (#1360)

---

js/hoverzoom.js
manifest.json
plugins/raindrop.js

New plug-in for: raindrop.io (#1378)

---

plugins/imgur_a.js

Galleries are now correctly handled:

Fix for plug-in: imgur_a (#1377)

---

plugins/startpage.js

Tested on Chrome Version 128.0.6613.85 (Official Build) (64-bit)

Fix for plug-in: startpage.com (#1361)

---

manifest.json
plugins/meiye.js

New plugin for: meiye.art (#1414)

---

plugins/instagram.js

Fix for plugin: instagram (#1359)

---

manifest.json
plugins/lummi.js

New plug-in for: lummi.ai

---

plugins/kick_a.js
plugins/twitch_a.js

Update twitch_a.js & kick_a.js

---

js/hoverzoom.js
manifest.json
plugins/brave.js

For image search on search.brave.com
Not tested on Brave browser

New plug-in for: Brave Image Search (#1420)

---

manifest.json
plugins/furrynetwork.js

Tested on Firefox and Chrome
Sorry for the unnecessary extra commit, it's my first time making a pull request. I didn't know the pull request to my fork would be a commit.

New plug-in for: Furry Network

---

plugins/inkbunny.js

- Adds full url to $ajax request for Firefox compatibility
- Changes variables to better align with style guide
I tested it on chrome and firefox with no issues reported

Fix for plugin: inkbunny.net

---

js/background.js

Fix for #633
- Also updated the variable scopes and comments in background.js to match style guide.
- Tested on Firefox and Chrome.

Fix: Pixiv.net - Saving with shortcut does not work

---

plugins/paheal.js

Fix: Rule34 videos not loading

---

manifest.json
plugins/tenor.js

New plug-in for: Tenor

---

manifest.json
plugins/gifbin.js

- Status code 206 "Invalid URI. Load of media resource failed." shows after loading each gif, but they still load and play as expected.

Fix for plug in: Gifbin

---

plugins/fetlife.js

images weren't loading in user's galleries, probably from an API change. This fixes it

Fix for plugin: Fetlife

---

plugins/eksisozluk.js

It seems the site requires a referrer header when making an ajax request, which isn't being sent with chrome. I made a workaround by creating a link from the post's date and the link's href. There's probably a better method for this though, e.g. sending a referrer header with the ajax request

Fix plugin eksisozluk not working on chrome

---

js/options.js
js/popup.js

Requested by #1318
Initial tests show Enter now works as an action key. Not sure if there are cases it would cause issues.

Add Enter as action key

---

manifest.json
plugins/etejo.js

New plug in for: Etejo

---

plugins/furrynetwork.js

Fix for plug-in: Furry Network

---

plugins/rule34.js

Fix for plugin: rule34.xxx

---

_locales/en/messages.json
js/options.js

Automatically update copyright to current year

---

CONTRIBUTING.md

* This project has no documented code of conduct. Linking to the LICENSE makes no sense.
* This project does not list contributors in the README. Saying contributors will be listed is disingenuous and misleading.
* This project has no unit tests. Asking to add them where they make sense doesn't make much sense.
#1249 added the CONTRIBUTING file. How it came to be is not described or sourced, but it seems to be a template or inspired/or sourced from elsewhere/other projects. These corrections should make it more applicable and correct for this project.

Fix CONTRIBUTING.md errors

---

plugins/reddit.js

- Fixes #1499
- Fix for images, videos, and galleries not loading in card or compact view
- I tested on r/all and some other subreddits, and it worked.
- Tested on Firefox 133.0.3 (64-bit) with W10

Fix for plug in reddit

---

js/hoverzoom.js

- Fixes the "if" comparison so it doesn't always return true
- Resolves #1540

Fix: Mouse buttons not working as action keys

---

_locales/en/messages.json
js/common.js
js/hoverzoom.js
js/options.js
js/popup.js

Adds the ability to rotate the image 90 degrees clockwise repeatedly. R is the default key
edit: Fixed the boundary issue. The image info goes on the left side when rotated though, due to having to rotate hz.hzViewer
- Resolves #1254 and addresses #1551

Add rotate image action key

---

_locales/en/messages.json
html/options.html
js/hoverzoom.js

Added explicit support for MPEG-DASH

Fix for #1604
