extesy/hoverzoom

- html/options.html
- js/background.js
- js/common.js
- js/options.js
The code for navigation of albums with the mouse wheel was already supported, but there was no way to enable it via the options. I have added an entry for mouse wheel navigation in the options page.
> Added mouse wheel navigation to options.

- plugins/fetlife.js
FetLife changed over to picX.fetlife.com sometime in early/mid April--this fixes detection and strips the varnish cache token at the end.
> Fixed FetLife (Mid-April Site Change)

- plugins/fetlife.js
Fixes Hover Zoom in places without cache IDs (the change is to make GET parameters optional)--specifically, on-profile activity feed thumbnails and tiny profile thumbnails (like tally on images, events, etc).  Did some more testing on this one, sorry for the double-pull!
> Fixes Images Without Cache IDs

- plugins/imgur_a.js
Following https://github.com/extesy/hoverzoom/pull/97, matching the custom domain for StackOverflow wasn't enough.
Since the `createUrls` force the domain to `i.imgur.com` photo from SO generate confusion.
For example, this url http://i.stack.imgur.com/sgKzK.jpg will be converted to http://i.imgur.com/sgKzK.jpg which is (definitely) not the same one (even if they have the same hash).
This PR fix that problem by handling that case.
_Sorry for not testing my previous PR._
> Special case for StackOverflow custom domain

- manifest.json
- plugins/clips.twitch.js
While adding support for clips.twitch.tv, I looked at the method used
in both plugins/reddit.js and plugins/gfycat.js. I think it turned out
right, but I'm not 100% sure I did it "by the books". But it works, so
I've that going at least.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/172)
> Added support for clips.twitch.tv

- plugins/youtube_a.js
Fixes #132. This is done by checking if the current link has the class
.ytp-title-link in prepareVideoPreview. I tested this change on a number
of ways, and it doesn't look like it breaks functionality anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/176)
> Disabled youtube video preview in embeded iframe

- js/hoverzoom.js
Fixes #110. Some websites use css selectors that require the
title-attribute to be present for the styling to work. Subreddits does
this a lot for flairs, and with this change we let websites keep styles
that are based on the title-attribute being present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/177)
> Stop removing the title attribute

- plugins/1x.js
- plugins/blogcdn.js
Hi
This is my first pull request for HoverZoom, and hopefully not the last :fearful:
I fixed the js plugin: 1x.js
Fix was tested on 1x.com, it should have no impact anywhere else since plugin is only loaded on "*://*.1x.com/*" urls (according to manifest).
I'm new to GitHub (and to js!), so:
- please double-check!  
- comments/advices warmly welcomed!
Have a nice day :smiley: 
Fix details:
Added new search patterns:
-ld.
-sd.
-hd2.
-sq.
-square.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/179)
> Fix of plugin: 1x

- plugins/fetlife.js
Previously, sweeping the mouse across too many thumbnails would cause full-size versions to start to fight over the top of each other.  Also seems to glitch out on text links, not sure if that's FetLife's DOM rendering the sizes of them strangely or what.  I just removed text links from getting hovers.  (Really, Fet uses thumbnails very aggressively, so this isn't a UX problem).
> FetLife Switched to "mouseover" Events

- js/hoverzoom.js
There was a typo.  `this` referred to all titledElements.  `$(this)` refers to only the hover-zoomed thing.
> Prevent hoverzooming from removing titles of all titled things.

- js/hoverzoom.js
Example: 
page url=http://example.com/path/index
image on page is in relative path URL: photo.jpg
Previously, hoverzoom will load http://example.com//path/photo.jpg
Note the double slashes in the image path.
Usually, this won't create any problems until there are cookies involved.
If a cookie is set under path "/path", a browser will not send the cookie when loading "//path/photo.jpg".
This commit fixes the bug.
> bug fixed for relative path double slashes

- js/background.js
- js/common.js
- js/options.js
- js/popup.js
This PR fixes following warnings from #300 
1. "tabs.getAllInWindow" is deprecated or unimplemented
5. "app.getDetails" is deprecated or unimplemented
7. "tabs.getSelected" is deprecated or unimplemented
8. "app.getDetails" is deprecated or unimplemented
9. tabs.getSelected" is deprecated or unimplemented
> Fix some of addons.mozilla.org warnings

- manifest.json
Neither Firefox, Chrome or Edge recognize `locale` manifest key.
In addition, it also displays red warning on Chrome.
* https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-manifest-keys
* https://developer.chrome.com/extensions/manifest
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json
There is `default_locale` indeed, but no `locale`.
> There is no such manifest key as `locale`

- manifest.json
- plugins/wykop.js
wykop.pl is Polish social media website with over 5 million unique users visiting monthly.
This plugin allows for hoverzoom of "GFY" images (WEBM/MP4), because regular images and GIFs already work fine.
I swear it's my last issue or PR today :>
> Added wykop.pl plugin

- js/options.js
`runtime.getPackageDirectoryEntry()` API method is available only on Chrome and it's missing on Firefox and Edge.
It means `getPlugins()` function in `options.js` is broken on Firefox. Nothing is shown in Options page under Plugins tab.
I've replaced it with analysis of `content_scripts` in manifest. It finds all plugins and in the end whole functionality is same as before. Except now it won't list orphaned plugins like those in #303
> Replace Chrome specific runtime.getPackageDirectoryEntry()

- plugins/instagram.js
Use a trick that replaces the post URL with an easy to remember URL that automatically redirects to the full-size image, instead of the (inexplicably) low-rez one that Instagram uses.
> Instagram: use full-size image instead of the default one.

- js/hoverzoom.js
In `rotateGalleryImg(rot)`, if the next `hoverZoomGallerySrc` element is an array of possible URLs to try,
`loadNextGalleryImage()` will recurse infinitely on error (i.e. when the URL it's trying to reach is invalid). When attaching handlers to `imgFullSize` in `loadNextGalleryImage()`, the error handler should probably be `imgFullSizeOnError` instead of recursing back into `loadNextGalleryImage`.
> Fixed loadNextGalleryImage() recursing infinitely on error

- js/popup.js
This fixes issue #423 created by myself. Currently the code didn't account for multiple windows being opened and tabs.query returns an array, the code was not accounting for that
> fix disable current site feature in popup

- js/hoverzoom.js
- plugins/reddit.js
I've found that a lot of videos on v.redd.it won't load with hoverzoom because the URL `/DASH_600_K` doesn't exist for that video. This updates the code that handles getting video links to request the `DASHPlaylist.mpd` file, which contains info about the available video resolutions, and then choose the highest resolution.
Additionally, the `DASHPlaylist.mpd` will contain info about audio streams, when available, so I've added functionality to support playing audio from a separate source URL than the video. When a separate audio source is specified via the `hoverZoomAudioSrc` data key, an HTML `audio` element will be created along with the `video`, and their playbacks will be kept in sync.
> Handle v.redd.it videos reliably and support audio

- plugins/streamable_a.js
Streamable videos (e.g. https://streamable.com/rq6ui) no longer have a `source` element, the source of the video is just on the `video` element.
> Fix streamable

- manifest.json
- plugins/hiptest.js
This is a plugin to directly preview tests attachments in test on Hiptest.com
Those attachments are files served by a link to an url like: https://app.hiptest.com/projects/124207/scenarios/3020680/attachments/151499
I didn't find how to just tell Hoverzoom to use the links I found, so I added a dummy regex.
Why is the thumbnail url forced to be different from the original picture ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/extesy/hoverzoom/442)
> Plugin for Hiptest.com tests attachments

- manifest.json
- plugins/twimg.js
- Added another urlReplace on twimg.js to account for the new mapping for the thumbnail and the full-size image.
- Also turned off the pointer-events for the new div that is covering the profile thumbs, and is preventing hoverzoom from accessing the <img> element.
> #455: Fix for profile images on Twitter no longer loading

- js/hoverzoom.js
Added binding to deal with lazy-loading:  prepare imgs links when user scrolls down more than x pixels
> Fix for lazy-loading

- plugins/tumblr_a.js
Hi!
This fixes https://github.com/extesy/hoverzoom/issues/496.
> Update Tumblr plugin

- plugins/twimg.js
Profile images in quoted tweets are not inside `<a>` tags and still don't load. But the profile popup appears and the profile image in the popup does load if hovered.
> Twitter: Fix loading profile images

- plugins/e621.js
Original image URL is contained in the data-file-url attribute so use it
instead of guessing. Hovering on WebM files works now and only one
image is requested
> Fix e621/e926 unreliable image hovering

- js/background.js
Firefox url is located at sender.url, copy sender.url to sender.tab.url
> Fix firefox not showing page action icon

- js/hoverzoom.js
Changing the mode to `no-cors` seems to fix the saving issue on #633. 
I test it on pixiv.net and artstation.com and they both work fine.
might need more testing on another website.
Tested on Chromium 87
> Fix CORS downloads

- _locales/en/messages.json
- css/style.css
- html/options.html
- html/popup.html
- js/common.js
- js/hoverzoom.js
- js/options.js
1. Option to save files to a user-defined subdirectory
As stated in Chrome API reference (https://developer.chrome.com/docs/extensions/reference/downloads/#type-DownloadOptions), no extension is allowed to download files to another directory than default Downloads.
But it is allowed to specify subdirectories **under** Downloads, so downloaded files can be managed more easily.
So under Options/Advanced, i added an new option to specify a subdirectory for downloads.
This option is facultory: if left blank then downloads will be saved to default Downloads directory, as usual.
2. Options now have 3 buttons:
- Save: save edits
- Cancel: cancel edits made after last save
- Reset: discard edits and load default values
3. Some cosmetic changes to buttons and input zones in Options
> Enhancement: save files to specific subdirectory

- _locales/en/messages.json
- html/options.html
- js/background.js
- js/common.js
- js/hoverzoom.js
- js/options.js
- js/viewWindow.js
HTTPS sites such as Google Images prevent loading of HTTP urls.
When this option is enabled, HZ+ will try to open unloadable urls in a **new tab or window**.
Note: this option is **disabled** by default.
Preview:
> New option: open unloadable urls in new tab or window

- _locales/en/messages.json
- html/options.html
- js/common.js
- js/hoverzoom.js
- js/options.js
@extesy, i first decided to remove all spinners (green, orange, red) but i changed my mind and kept the green one. 
I spared it because it's the only visual clue for users that HZ+ is actually doing something (=trying to zoom the image under mouse pointer!).
Another option whould be to modify the look of image being hovered, like Imagus that adds a dotted border around image.
I did some tests, it is not fully reliable, so maybe we should keep the green spinner for now, what do you think?
By default, red and future orange spinners are disabled.
> Fix for red spinner: now not displayed by default

- plugins/500px.js
- plugins/facebook.js
Added a call to : hoverZoom.displayPicFromElement(link) to force immediate display of zoomed pictures
> Speed-up images display in 500px & Facebook plug-ins

- plugins/imgur_a.js
Added a fix in case Imgur links are pasted in Google Sheets.
This fix closes #523
> Fix for plug-in: Imgur

- plugins/facebook.js
March, 2021 : Facebook modified the way **fb_dtsg** value is stored in document, this fix handles the new storage method.
> Fix for plug-in: Facebook

- _locales/en/messages.json
- js/common.js
- js/hoverzoom.js
- "**panic mode**": **ESC key now closes zoomed images** (some users are probably not aware of the Hide action-key, whereas Escape key usage is well-known)
- fix #638 : "Audio for Hoverzoome'd video will play in background even after video closes"
- fix rare bug with background images
- update version & copyright footer
> Little improvements

- js/hoverzoom.js
Running a regEx on embedded images'urls like this one: 
_data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==_
is :
- **useless** since they will not be zommed,
- **problematic** when base64 encoded string of the image is thousands of characters long : in such case regEx can cost **dozen of seconds to evaluate**, causing browser freeze (#715).
So they must be filtered out (this applies to regular & background images)
> Fix for embedded images

- _locales/en/messages.json
- html/options.html
- js/common.js
- js/hoverzoom.js
- js/options.js
In order to ease management, filenames of saved images & videos can be prefixed with:
- **origin**
- **size**
- **duration** (videos only)
For instance, a 1200x900 picture saved fron DeviantArt with original filename: WhiteRabbit.jpg
will be renamed to: [www.deviantart.com][1200x900]WhiteRabbit.jpg
This option is **disabled** by default.
> New option: rename when saving images & videos

- _locales/en/messages.json
- html/options.html
- js/background.js
- js/common.js
- js/hoverzoom.js
- js/options.js
- js/viewWindow.js
- plugins/baidu.js
- plugins/default.js
- plugins/imgur_a.js
- plugins/photobucket.js
- plugins/ravelry.js
- new option: display image/video details (dimensions, filename...) above or below image/video (default: disabled)
- new option: font size for caption & details (default: 11px)
- new option: font outline for caption & details (default: disabled)
- new option: frame thickness (default: 4px)
- gallery index (1/3, 2/3, ...) now displayed in top-left corner of image/video (so it does not mix with timestamp in case of video)
- improvements to video display
- bugs fixed
- plugins updated
> New image/video viewer

- js/common.js
Follow-up to #768 by @George-lewis so action key L is for image locking by default.
> New action key for Copy Image URL : U

- _locales/en/messages.json
- html/options.html
- js/common.js
- js/hoverzoom.js
- js/options.js
Rework of #740 by @Mattwmaster58 : a new section "Troubleshooting" is added to Advanced Options page.
By default, debug is **disabled**.
> New Advanced option: enable debug

- manifest.json
- plugins/duckduckgo.js
- plugins/googlesheets.js
- plugins/qwant.js
and also some minor changes for  Qwant & DuckDuckGo plug-ins
> New plug-in for: Google Sheets

- manifest.json
HLS.js (unminified) is quite big (~ 1MB) and should be loaded only when needed in order to play M3U8 (like in Twitch.tv).
> Load HLS.js only for Twitch

- _locales/en/messages.json
- js/hoverzoom.js
To start video playback, user must first interact with the page or there is an error message:
NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
A (blinking) text message reminds user to do so:
> Enhancement: display an error msg when a video does not start

- _locales/en/messages.json
- html/options.html
- js/background.js
- js/options.js
- Link to **Changelog** in footer.
- Display **date of installation or last update** in footer on Options pages. This additional info will help users detect & (hopefully) report regressions.
> Improvements on Options page

- _locales/en/messages.json
- js/common.js
- js/hoverzoom.js
- js/options.js
2 keys added:
- "Toggle HZ+": quick way to enable/disble HZ+ without using Options page (default key: E)
- "Close image": close image (or video) being zoomed, instead of just hiding it temporarily (default key: ESC)
Some rewording to make these settings less confusing (i hope)
> Rework of Action keys

- js/hoverzoom.js
@extesy @mobad @JunoArc 
Actually there are 2 distinct issues:
- **adding urls of zoomed images & videos to browser's history**: this works fine (on all sites, not only Reddit), it was the purpose of #873 
- **turning links color to purple once hovered**: this does not work if image's url differs from link's href, as in Reddit. So i also added href to history (as suggested by @mobad)
> Fix for: #881

- _locales/en/messages.json
- css/style.css
- html/options.html
- html/popup.html
- js/options.js
- js/popup.js
Some HZ+ users are not aware of existence of action keys and miss out many functionalities (lock, save to disk...).
That's probably because action keys setting is hard to reach, users need to:
- click "Extension menu" puzzle icon
- click "More actions" 3-dots icon
- select "Options" in menu
- select "Action keys" in Options
So i replaced the old popup by a new one for action keys reachable in 2 clicks:
- click "Extension menu" puzzle icon:
- click "Hover Zoom+":
Note: classic "Action keys" settings in Options are unchanged.
> New popup for action keys

- _locales/ko/messages.json
- _locales/pt_PT/messages.json
- manifest.json
@extesy you removed **"all_frames": true** directives from manifest for all plug-ins.
This breaks Bing plug-in, so i put it back. Hopefully it does not break any other plug-in...
BTW, why not allowing all plug-ins to run in all frames?
> Manifest: Bing plug-in must run in all frames

- manifest.json
- plugins/tiktok_a.js
> New plug-in for: TikTok

- _locales/en/messages.json
- html/options.html
- js/background.js
- js/common.js
- js/options.js
- manifest.json
- plugins/dailymotion_a.js
There's a new Advanced option: 
By default, this option is **disabled**.
When enabled, HZ+ can now deal with CORS mechanism, as if a specific extension such as SMH (https://chrome.google.com/webstore/detail/simple-modify-headers/gjgiipmpldkpbdfjkgofildhapegmmic), was installed along with HZ+. (Note: SMH is used with Imagus)
The big benefit is that users do not have to install & tweak SMH or similar tool - which is a tedious task - because plug-ins will handle headers rewrite by themselves. 
For now, the only plug-in that uses this feature is **Dailymotion**. As a result, videos from Dailymotion can be zoomed & played from Google & Bing search pages, from Reddit & other sites.
2 optional permissions are added to manifest:
"**webRequest**"
"**webRequestBlocking**"
These permissions are …
> New Advanced option + new plug-in: Dailymotion

- _locales/en/messages.json
- js/hoverzoom.js
Sometimes action keys seem to be broken, this usually happens when page has lost focus.
A warning message will ask user to click anywhere on page so it has focus and action keys can work.
This message is displayed only once (until page is reloaded), so users that do not use action keys are not bothered.
> New warning message when page is not focused

- plugins/youtube_a.js
- select video with max width available (any format)
- play links with timestart (e.g: https://youtu.be/qORYO0atB6g?t=28)
> Fix for plug-in: YouTube_a

- js/background.js
- js/hoverzoom.js
- zoom improved for large images (> 1000px)
- "Lock" action key improved:
- 1st keypress: image/video displayed **fullsize** so user can pan around
- 2nd keypress: image/video **fit the screen**
> Various enhancements

- js/hls.js
Removes this warning from the console.
For most users it's likely not an issue, for web developers it's a pain having it log out to the console.
> Remove source mapping comment from hls.js

- _locales/en/messages.json
- css/style.css
- html/options.html
- html/popup.html
- js/common.js
- js/options.js
- js/popup.js
\+ minor improvements (new font, ...).
By default, dark mode is **disabled**.
Preview:
> Dark mode for HZ+ Options pages & popup window (#1028)

- _locales/hu/messages.json
- plugins/homeexchange.js
Hello @hytea 
I found a weird bug with  ~MomExchange~HomeExchange (not your plug-in, the website) : if you use `"?quality=100&height=1080&width=1080"` as a query then website'll just send back original image (= fullsize) most of the time.
So i made some changes :-)
Thank you for contributing, any other plug-in welcomed!
GP
> Follow-up to HomeExchange plug-in (#1043)

- plugins/reddit.js
Gallery ID can be 7 chars long, like it was done in `a` selector. Change both implementations to get gallery ids regardless of length
> Fix getting galleryid in reddit plugin

- manifest.json
- plugins/fandom.js
This plug-in zooms images & videos.
> New plug-in for: fandom.com (#1077)

- README.md
The list of supported sites is not easy to find. This is obvious to you as the author, but I needed to go from the addons page to the repository, read the readme, enter a query into the search, and only on the second page of results I understand that each supported site is a separate file in the plugins folder. It took some time. And not every addon user will be able to find it. But I think a lot of people will. 
This PR is just a simple example of how you can help the user find the list. But this is a bad solution to the problem. I would recommend that you provide a link to such information on the addon page. You can also add a list opening from an already installed addon.
> Add a link to the list of plugins in the readme

- js/hoverzoom.js
- keep same viewer when switching from image to image
- recreate viewer when switching to video, audio or playlist
> Fix for #1092

- manifest.json
- plugins/omegle_a.js
Warning: Omegle logs are hosted on HTTP. To display them from HTTPS sites (e.g: google search) you have to enable  this option (Options -> General) :
> New plug-in for: Omegle

- js/background.js
- js/hoverzoom.js
HZ+ first tries to download a file using Chrome API (chrome.downloads.download).
Download **will succeed in most cases** and downloaded files will have correct extensions, even if  "Double-click Image Downloader" or "image Downloader" extensions are active.
But some sites prevent direct download, such as Pixiv, so if download fails then HZ+ will use a workaround:
1. obtain ArrayBuffer from XHR request (GET URL)
2. create Blob from ArrayBuffer
3. download Blob URL through Chrome API (chrome.downloads.download)
Then 2 cases:
- "Double-click Image Downloader" or "image Downloader" extensions are NOT active: file extensions are correct.
- "Double-click Image Downloader" or "image Downloader" extensions are active: file extensions are missing, they must be added by hand.
> Fix for missing file extension after download (#1116)

- js/background.js
- js/hoverzoom.js
Sometimes, for some unknown reason, callback for download retry is called even if download succeded.
=> protection added against "parasite" callback calls
> Fix for multiple downloads when saving a file (#1127)

- js/background.js
- js/hoverzoom.js
When setting "Ask where to save each file before downloading" is enabled, user cancel must be handled.
> Fix for #1127

- js/hoverzoom.js
For pixiv.net: use "blob" workaround on first download attempt as regular download always fails.
> Improvement of file downloads for Pixiv.net

- _locales/en/messages.json
- html/options.html
- js/hoverzoom.js
When an image or video is locked on screen, it can be zoomed in or out using mouse wheel.
- press + or ↑ while scrolling to zoom **faster**
- press − or ↓ while scrolling to zoom **slower**
Update of options page:
> Improvement for zoom in/out on locked images & videos

- plugins/shein.js
This fix addresses cover-protection in order to let users save full-size images.
> Fix for plug-in : Shein (#1203)

- js/hoverzoom.js
- package.json
Pass the event object to the function as it's used there.
Fix #1036
> fix: panning locked images+videos on firefox

- plugins/redgifs.js
currently selector does not support http link, this should work for all giphy links
> add support for redgifs links including http

- manifest.json
- plugins/shirt_woot.js
- plugins/woot.js
Sample URL: https://shirt.woot.com/plus/5-shirts-for-30
All the images have a `._SX240_` suffix, wasn't sure the best way to replace it, but this worked. Open to suggestions.
> add support for woot.com

- js/hoverzoom.js
A playlist is saved to 3 distinct files:
- playlist itself (M3U8)
- audio (MP3)
- video (MP4)
TODO : mux audio & video into one single file.
This could be done with ffmpeg.js, but this lib is pretty big :worried:
@extesy any better idea ?
> Save playlists (M3U8) to audio & video files

- manifest.json
- plugins/lensdump_a.js
I have no idea what I'm doing, but this seems to work on the Reddit post I linked in the original issue.
Fixes #1234.
> Add support for lensdump links

- _locales/hr/messages.json
- js/hoverzoom.js
MPEG-DASH MPD videos are converted to M3U8 playlists so HLS.js can play them.
This feature is needed for Facebook lives, for instance.
> Support for MPEG-DASH MPD videos

- js/hoverzoom.js
- manifest.json
- plugins/google_a.js
- plugins/googledrive.js
Google Drive plug-in zooms images & also non-images documents, such as XLS files, PowerPoint,...
> New plug-in for: Google Drive + fix for Google Photos + old bug fix

- js/hoverzoom.js
flash support is long gone. the TODO to remove it is 1.5y old.
> chore: remove flash fix

- plugins/imdb.js
> Update for plug-in: imdb.com

- manifest.json
- plugins/tapas.js
This introduces functionality for the tapas.io website. The changes allow the extension to discover and prepare images from tapas.io.
- Added a new plugin for tapas.io in the hoverZoomPlugins array.
- The plugin includes a configuration object for tapas.io specific selectors and classes.
- Implemented `awaitDom` function to wait for an element to appear in the DOM.
- Implemented `prepareComics` function to prepare the comics for HoverZoom+ to discover.
- The plugin initiates an episode listener that triggers `prepareComics` when new images load.
These changes add support for the tapas.io website to the hoverZoom plugin, enhancing the plugin's functionality.
> Implement tapas.io plugin

- plugins/redgifs.js
Redgifs started to throw 429 Rate limit when requesting to often to temporary token. This PR stores it in variable and reuses it.
> feat: store redgifs token to avoid hitting rate limit

- plugins/mediawiki_a.js
Use a less precise attribute selector since mediawiki thumbnail URLs no longer use the full URL
E.g. https://runescape.wiki/
> Fix mediawiki plugin thumbnail selector

- _locales/en/messages.json
- html/options.html
- js/common.js
- js/hoverzoom.js
- js/options.js
For instance, third image out of ten is saved as: [03-10]image.jpg 
This option eases sorting of saved images.
By default, this option is **disabled**.
> New option: add index of image in gallery when saving

- _locales/en/messages.json
- html/options.html
- js/common.js
- js/hoverzoom.js
- js/options.js
For instance, an image of Mona Lisa is saved as: `[Mona Lisa by Leonardo da Vinci]image03.jpg`
By default, this option is **disabled**.
This new option is available in Advanced options:
> New option: add caption to filename when saving

- _locales/en/messages.json
- html/options.html
- js/common.js
- js/hoverzoom.js
- js/options.js
Original filenames might be meaningless (e.g: 125487_asdfg.jpg)
This option allows replacing them by something more relevant.
Extensions are preserved.
If option is enabled and no replacement is given then original filename is removed.
By default, this option is **disabled**.
This new option is available in Advanced options:
> New feature : replace original filename when saving

- plugins/linkedin.js
> This PR fixes an issue with LinkedIn profile pictures containing tags like 'hiring' or 'open to work' that were not zooming correctly in the HoverZoom extension.
Previously, the code assumed that the 4th image in the LinkedIn API response was always the largest one. However, in cases where profile tags such as 'hiring' or 'open to work' are present, the 4th image is actually the smallest. This PR updates the image selection logic to handle such cases, ensuring that the correct (largest) image is used for zooming, regardless of the presence of these tags.
> Fix: LinkedIn profile pictures with 'hiring' or 'open to work' tags not zooming correctly

- js/hoverzoom.js
In hoverzoom.js, changes:
```js
doc.open(); 
doc.write(data);
doc.close();
```
to 
```js
doc.body.innerHTML = data;
```
- This fixes it giving the following error on Firefox: `"SecurityError: The operation is insecure."`
- Also updated variable scopes to match the style guide.
This will fix some plugins on Firefox that rely on prepareFromDocument() to function. Issue #429 is fixed with this, and there might be more. I tested it on Chrome and Firefox, and it worked for me.
> Fix: Function prepareFromDocument() breaking on Firefox

- js/background.js
Fix for #1387
Changes:
```js
chrome.permissions.request({permissions: ['downloads']}, function (granted) {
cLog('downloadFile granted: ' + granted);
if (granted) {
...
}
});
```
to
```js
chrome.permissions.contains({permissions: ['downloads']}, (contained) => {
cLog('downloadFile contains: ' + contained);
if (contained) {
...
} else {
chrome.permissions.request({permissions: ['downloads']}, (granted) => {
cLog('downloadFile granted: ' + granted);
if (granted) {
...
}
})
}
});
```
This fixes images not downloading on Firefox, and still allows chrome to request permissions via a prompt. It is not an ideal fix, but until this bug is resolved on Firefox's end, this is the best fix I found.
> Fix: "Save image" Action Key does not work

- plugins/furaffinity.js
I fixed images flickering when you move your mouse around while hovering over one.
- Made prepareFromDocument callback function return a full url
```js
return img ? img.dataset.fullviewSrc : null;
```
to
```js
return img ? 'https:' + img.dataset.fullviewSrc : null;
```
- Updated variable scopes
> Fix: Hovered images flicker on Fur Affinity

- _locales/en/messages.json
- html/options.html
- js/common.js
- js/hoverzoom.js
- js/options.js
Requested option from issue #1216
- Locks image whenever Hover Zoom activates. Added option for it in the options page. Only has English name and tooltip.
- Tested in Firefox and Chrome
> Add 'Automatically lock images' function

- js/hoverzoom.js
From issue #570
- When pressing the 'Full Zoom' button, the image will expand to window's size + padding.
- Fullzoom might look better if the image could stretch to completely to bottom of window, but this implementation works.
- Tested on Firefox and Chrome
> Fix: Fullzoom button not filling window

- plugins/reddit.js
Made sh.reddit search and compact view media load.
- In searches, selecting only the thumbnails allowed it to load, while in normal compact view, selecting the whole faceplate allowed it to load. Not sure why. I want to streamline it, but for now, things work as expected.
- Might allow searches to load media in old.reddit as well in the future
> Fix: sh.reddit.com search and compact view not loading

- plugins/github.js
Images on github with a src containing "private-user-images" wasn't loading before. This fixes that. I discovered the issue when looking at issues on the hz+ repository.
> Fix: GitHub not loading private user images

- js/hoverzoom.js
Variable 'body100pct' in hoverzoom.js is not picking up Fur Affinity using max-width which sets hzWindow position wrong when innerWidth is greater than max-width. This fix makes body100pct check if max-width is changed in the body's css, returning false if it is.
> Fix: Zoomed images's horizontal position wrong on Fur Affinity on 2k monitors

- _locales/en/messages.json
- html/options.html
- js/common.js
- js/options.js
Adds an import and export box under the "Advanced" tab.
- Exports options in a json string format
- Has checks for valid HZ+ JSON string when importing
- Shows changed options upon importing (glows like when changing options)
Remedies #804 and #687
> Add import/export function

- js/common.js
- js/hoverzoom.js
- js/options.js
- js/popup.js
Fully adds right click and middle click as an action key. Before, right key was showing as an action key but was only being handled for 'lockImage'. This updates it so right click and middle click are completely useable as a key.
- Middle click still does it's normal function, even after HZ+ function triggers. Right click doesn't
- event.preventDefault() wasn't working to fix the issue, even after trying many things with it. 
- The hold delay is set to 150ms. It felt short enough to not wait, but it was long enough to not trigger accidentally
- Some buttons that don't require an image to be shown might trigger accidentally with normal use. E.g. toggle HZ+ when it's set to middle mouse click.
- The performance hit shouldn't be noticeable as a switch case is used to handle mouse events, but …
> Add middle click and right click as action keys

- plugins/github.js
image sources with user-image urls on github weren't zooming. This fixes it.
> Fix: Github user images not zooming

- js/hoverzoom.js
Pressing middle click as an action key would cause right click to not have a context menu, if pressed while middle clicked was held.
> Fix middle click's timer affecting right click's context menu

- plugins/slickdeals.js
This updates it to work with changes to the site. It's also backwards compatible, and won't affect places the plugin is currently working.
> Fix slickdeals plugin

- plugins/kleinanzeigen.js
Image galleries are now correctly displayed.
> Fix for plugin: kleinanzeigen.de (#1471)

- _locales/en/messages.json
- css/style.css
- html/options.html
- js/background.js
- js/common.js
- js/hoverzoom.js
- js/options.js
- js/popup.js
A new action key (default value: "B") can be used to prevent an image, video or audio track from being zoomed (and played) next time it is hovered. 
Ban is not lifted by just restarting browser. So in Advanced options, a new button is available in order to reset banned items so they can be zoomed again.
> New action key: ban an image, video or audio track

- js/hoverzoom.js
- Fixes #1504
- When Ambiant light is on, hzAbove and hzBelow are null. This broke a new setting
> Fix: ambiant light making images not show

- js/hoverzoom.js
- This might fix the issue described in https://github.com/extesy/hoverzoom/pull/1489#issuecomment-2564391188
> Fix: images showing when mouse is off image link

- js/hoverzoom.js
- This fixes what #1515 was trying to fix
- setLoadImage used to set loadHoveredImage within callback so timeout can be set outside of callback. This makes clearTimeout use the correct timeout ID
- There is probably a smarter way of fixing this, but this works
> Fix: loadFullSizeImageImageTimeout not clearing when mouse leaves image

- manifest.json
This updates the manifest with```browser_specific_settings```which Firefox requires for storage.sync API, mainly the addon ID: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync
- The ID used is the permanent ID assigned by AMO
> Add Addon ID to manifest for storage.sync support in firefox

- plugins/wordpress_a.js
Turn this:
https://i0.wp.com/lgbtqreads.com/wp-content/uploads/2024/02/JFP_MMN_COV_mksm.jpg?resize=197%2C300&ssl=1
into this:
https://i0.wp.com/lgbtqreads.com/wp-content/uploads/2024/02/JFP_MMN_COV_mksm.jpg
Also avoid breaking URLs with a resolution baked into the file name if they also have queries at the end:
https://i0.wp.com/lgbtqreads.com/wp-content/uploads/2024/12/ItsaLoveSkateRelationship-hc-c-678x1024-1.jpg?resize=199%2C300&ssl=1
"-678x1024" is supposed to be there.
Also handle URLs that don't have "wp-content" in them even though they're hosted at i0.wp.com:
https://i0.wp.com/i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1665507126l/58762417._SX318_.jpg?resize=187%2C279&ssl=1
Technically some of these should also have the ``._crap_`` removed, but I had enough. …
> Wordpress: Fix URLs with queries

- manifest.json
- plugins/media-amazon_a.js
Turn this:
https://m.media-amazon.com/images/I/817lsQFcS2L._SL1500_.jpg
into this:
https://m.media-amazon.com/images/I/817lsQFcS2L.jpg
I assume these can be found on any site, so the plugin matches all URLs.
Test page:
https://lgbtqreads.com/2025/02/05/happy-national-girls-and-women-in-sports-day-2025/
(Scroll down to "Playing for Keeps".)
> New plugin: m.media-amazon.com

- js/hoverzoom.js
- Fixes #1536
Mouse event handler returns if click is not right or middle click
> Fix: Mouse Back/Forwards break right click with HZ+ enabled

- js/hoverzoom.js
Match requires variable to be a string in Firefox. This converts ```headers``` to a string so ```headers.match``` doesn't throw a TypeError message in Firefox
> Fix: TypeError message in Firefox

- _locales/en/messages.json
- html/options.html
- js/options.js
- Should be a fix for those who's settings didn't migrate
- Working on a fix to migrate options function too
> Add migrate old settings button

- js/hoverzoom.js
- Should resolve #1374
- Changes "Lock Image" so the first press will make the image fit the screen and the second press will make the image larger than the screen, on images large enough for it.
> Make lock image not start zoomed in

- manifest.json
Firefox 136 still needs background.scripts in the manifest to work. This adds it
> Fix V3 Manifest

- plugins/reddit.js
This may just support sh.reddit embeds, haven't tested in old.reddit
> Fix: Embedded images on reddit not zooming

- js/common.js
Adds \ as a selectable action key. Resolves #1575
> Add \ as action key

- _locales/en/messages.json
- html/options.html
- js/common.js
- js/hoverzoom.js
- js/options.js
Adds options to toggle viewer shadow and caption/details shadows
> Add shadow toggle options

- js/background.js
As described here: https://github.com/extesy/hoverzoom/issues/1585#issuecomment-2755606050:
Fixes dataURIs not downloading in Firefox by making the blobUrl an ObjectURL instead:
https://github.com/extesy/hoverzoom/blob/59dce25a66e89dfa26579bc44c4a7dce1e7cbaaa/js/background.js#L55
to
```js
const isChromiumBased = !!navigator.userAgentData?.brands?.some(item => item.brand === 'Chromium')
const blobUrl = isChromiumBased ? await blobToDataURI(blobBin) : URL.createObjectURL(blobBin);
```
> Fix BlobUrl not downloading in Firefox

- _locales/en/messages.json
- html/options.html
- js/background.js
- js/common.js
- js/hoverzoom.js
- js/options.js
- manifest.json
- Adds a new checkbox in the advanced tab of the options page which is used to request 'downloads' permission
- Both Firefox and Chrome get a prompt requesting the user to grant permission when the checkbox is ticked
- No longer requires 'downloads' permission to work
- Resolves #1584
> Make downloads permission optional

- js/background.js
- js/hoverzoom.js
- js/options.js
This allows hoverzoom.js to check for 'downloads' permission before saving an image, in case the permission was already active or changed outside the options page.  This also allows an alert to be sent from the main script. The permission could instead be checked in hoverzoom.js ```init()``` so it's not called every time a user tries to save an image
> Add permissions checking function to background

- js/hoverzoom.js
- js/options.js
- manifest.json
- ruleset.json
This attempts to fix "Copy Image" and "Copy Image URL" so it works in Chrome and Firefox. The main issue is Chrome requires "Access-Control-Allow-Origin" headers to be set. This is infeasible as it would have to be set for every site, unless it is set when the "Copy Image" key is pressed
- will fix #1607 once cors issue is resolved
> Fix copy image and copy image url

- _locales/en/messages.json
- html/options.html
- js/common.js
- js/hoverzoom.js
- js/options.js
The new option, `galleriesLoopEnabled`, is true by default. If disabled, navigating past the beginning or end of an album will do nothing, rather than looping back to the other side of it.
I created this PR after I realized that I could just do https://github.com/extesy/hoverzoom/issues/1618 myself. :)
Unfortunately, I have no idea how to create all the translations for the option description, so that'll have to be done before this PR can be accepted. Is there some script I can run that will auto-translate the `en` locale message that I did write?
> Added an option to disable looping albums

- plugins/pixiv.js
This is a two-fold improvement for the Pixiv plugin:
1. This fixes a bug that caused PNG files to not be downloadable via the Save Image action. HZ would instead save the "master1200" thumbnail, which is a lower resolution JPG.
2. While fixing that, I also realized how to dramatically improve the performance of scrolling through a zoomed high-res gallery. Now, regardless of which format each file is in, they should load near-instantly while scrolling, especially with preloading enabled. 
Previously, PNG-based galleries would take about a half-second to load each image, during which the zoom would disappear, which was really jarring.
> Pixiv plugin fix for PNGs, also improved performance

- js/background.js
The [`chrome.tabs.query({active: true})`](https://developer.chrome.com/docs/extensions/reference/api/tabs#method-query) returns a list of active tabs across *all* browser windows. This means that picking `tabs[0]` doesn't necessarily correspond to the current window which can cause new tabs to be positioned in odd locations.
Additionally, the original implementation chose to open a new tab after the current tab only in case of background tabs (using `shift`). Non-`shift` uses opened the new tab at the current index, which had the effect of seemingly opening the new tab *before* the current tab. This has been simplified to always open a new tab *after* the current tab.
Fixes #1649 
Might also possibly be a fix for the odd behaviour explained in #336
> Always open new tabs next to the current tab
